// flow-typed signature: f57fa64c29e5a9a44853ed3396f47670
// flow-typed version: <<STUB>>/eslint-config-esnext_v^2.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-esnext'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-esnext' {
  declare module.exports: any;
}
