// flow-typed signature: 5229dd8fd21b776d0bdbc1764249702b
// flow-typed version: <<STUB>>/eslint-config-node_v^3.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-node' {
  declare module.exports: any;
}
