// flow-typed signature: 3d1fe12ef1d8c0b36c3e0ac6832ba16d
// flow-typed version: <<STUB>>/react-scripts-ts_v^2.17.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scripts-ts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-scripts-ts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-scripts-ts/bin/react-scripts-ts' {
  declare module.exports: any;
}

declare module 'react-scripts-ts/config/env' {
  declare module.exports: any;
}

declare module 'react-scripts-ts/config/jest/babelTransform' {
  declare module.exports: any;
}

declare module 'react-scripts-ts/config/jest/cssTransform' {
  declare module.exports: any;
}

declare module 'react-scripts-ts/config/jest/fileTransform' {
  declare module.exports: any;
}

declare module 'react-scripts-ts/config/jest/typescriptTransform' {
  declare module.exports: any;
}

declare module 'react-scripts-ts/config/paths' {
  declare module.exports: any;
}

declare module 'react-scripts-ts/config/polyfills' {
  declare module.exports: any;
}

declare module 'react-scripts-ts/config/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'react-scripts-ts/config/webpack.config.prod' {
  declare module.exports: any;
}

declare module 'react-scripts-ts/config/webpackDevServer.config' {
  declare module.exports: any;
}

declare module 'react-scripts-ts/scripts/build' {
  declare module.exports: any;
}

declare module 'react-scripts-ts/scripts/eject' {
  declare module.exports: any;
}

declare module 'react-scripts-ts/scripts/init' {
  declare module.exports: any;
}

declare module 'react-scripts-ts/scripts/start' {
  declare module.exports: any;
}

declare module 'react-scripts-ts/scripts/test' {
  declare module.exports: any;
}

declare module 'react-scripts-ts/scripts/utils/createJestConfig' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-scripts-ts/bin/react-scripts-ts.js' {
  declare module.exports: $Exports<'react-scripts-ts/bin/react-scripts-ts'>;
}
declare module 'react-scripts-ts/config/env.js' {
  declare module.exports: $Exports<'react-scripts-ts/config/env'>;
}
declare module 'react-scripts-ts/config/jest/babelTransform.js' {
  declare module.exports: $Exports<'react-scripts-ts/config/jest/babelTransform'>;
}
declare module 'react-scripts-ts/config/jest/cssTransform.js' {
  declare module.exports: $Exports<'react-scripts-ts/config/jest/cssTransform'>;
}
declare module 'react-scripts-ts/config/jest/fileTransform.js' {
  declare module.exports: $Exports<'react-scripts-ts/config/jest/fileTransform'>;
}
declare module 'react-scripts-ts/config/jest/typescriptTransform.js' {
  declare module.exports: $Exports<'react-scripts-ts/config/jest/typescriptTransform'>;
}
declare module 'react-scripts-ts/config/paths.js' {
  declare module.exports: $Exports<'react-scripts-ts/config/paths'>;
}
declare module 'react-scripts-ts/config/polyfills.js' {
  declare module.exports: $Exports<'react-scripts-ts/config/polyfills'>;
}
declare module 'react-scripts-ts/config/webpack.config.dev.js' {
  declare module.exports: $Exports<'react-scripts-ts/config/webpack.config.dev'>;
}
declare module 'react-scripts-ts/config/webpack.config.prod.js' {
  declare module.exports: $Exports<'react-scripts-ts/config/webpack.config.prod'>;
}
declare module 'react-scripts-ts/config/webpackDevServer.config.js' {
  declare module.exports: $Exports<'react-scripts-ts/config/webpackDevServer.config'>;
}
declare module 'react-scripts-ts/scripts/build.js' {
  declare module.exports: $Exports<'react-scripts-ts/scripts/build'>;
}
declare module 'react-scripts-ts/scripts/eject.js' {
  declare module.exports: $Exports<'react-scripts-ts/scripts/eject'>;
}
declare module 'react-scripts-ts/scripts/init.js' {
  declare module.exports: $Exports<'react-scripts-ts/scripts/init'>;
}
declare module 'react-scripts-ts/scripts/start.js' {
  declare module.exports: $Exports<'react-scripts-ts/scripts/start'>;
}
declare module 'react-scripts-ts/scripts/test.js' {
  declare module.exports: $Exports<'react-scripts-ts/scripts/test'>;
}
declare module 'react-scripts-ts/scripts/utils/createJestConfig.js' {
  declare module.exports: $Exports<'react-scripts-ts/scripts/utils/createJestConfig'>;
}
